### ISSUE TITLE
fail to replicate the experiment

### ISSUE THREAD

**Issue by kaishxu** [ha-lins/GEML-MDG#3]
Hello!

I have some questions about the code.
1. can I use "our_geml_cy.py" to pretrain the model and "our_geml_eval_cy.py" to get the test result?
2. in "our_geml_cy.py", line 284, the code "symp_state[i][self.topic + j] = utter_hidden[i][j]" seems to be useless?
3. in "our_geml_cy.py", line 286, is it wrong to assign the value? "sym_mat[i][j][j:last] = torch.ones(1)" is to connect the neighbor two utterances, right? so it should be "sym_mat[i][self.topic+j][self.topic+j:self.topic+last] = torch.ones(1)".
4. i follow the "our_geml_cy.py" and "our_geml_eval_cy.py" and train the model with the dataset "cy" in 30 epochs, however, the predictions are all "这种情况多久了？"

**Comment by kaishxu** [comment]
As for the data, I have checked some data files and found that there are no merging for patients responses or doctor responses. If patient or doctor reply several sentenses separately, it should be merged and then put into training, right?

**Comment by kaishxu** [comment]
Another question about the code is about "graph-evolve".
In the file "our_geml_cy.py" and other similar files, the evolving module is writen like:
"for symp_i in his_symptoms:
    for symp_j in his_symptoms:
        self.evovl_mat[symp_i][symp_j] = 1"
it is weird since the shape of "his_symptoms" is [bs * symp_size], and symp_i and symp_j are from different sample. In paper, the evolving happens in history entities of one dialogue.

**Comment by ha-lins** [comment]
Hi, @KaishuaiXu
  
Thanks for your interests! Pls check the script `run.sh` for the pretraining and fine-tuning pipeline. We first use the `train` mode to pretrain over many source diseases and obtain the meta-model, then we use 'fine-tune' mode to perform the adaptation to each target disease. Finally, we perform testing over each target disease with the `evaluate` mode. The whole pipeline needs the modification to the configuration of the `json` file. Pls double check the right configuration of the `json` file. 

For the data, we split a complete dialogue sample into many samples according to different turns. You can treat it as the task of single-turn dialogue while the context history is multi-turn. Thus we don't need to merge it.

The newly-coming entities are from the batch data could be better than from merely one sample, since the KG can be enriched much more.
